apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-cicd-demo
  template:
    metadata:
      labels:
        app: go-cicd-demo
    spec:
      containers:
        - name: go-cicd
          image: 481071950406.dkr.ecr.ap-south-2.amazonaws.com/go-cicd-demo:latest
          ports:
            - containerPort: 80

